total_reallocation_number = 50

[layer_0]
q_proj = 0
v_proj = 0
residual_1 = 1
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 38
residual_1 = 19
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 15

[layer_2]
q_proj = 0
v_proj = 47
residual_1 = 0
residual_2 = 0
shortcut_sa = 36
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 1
residual_1 = 0
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 1

[layer_4]
q_proj = 0
v_proj = 48
residual_1 = 0
residual_2 = 1
shortcut_sa = 37
shortcut_ffn = 0

[layer_5]
q_proj = 0
v_proj = 1
residual_1 = 7
residual_2 = 5
shortcut_sa = 5
shortcut_ffn = 2

[layer_6]
q_proj = 0
v_proj = 49
residual_1 = 1
residual_2 = 0
shortcut_sa = 41
shortcut_ffn = 0

[layer_7]
q_proj = 0
v_proj = 0
residual_1 = 1
residual_2 = 1
shortcut_sa = 39
shortcut_ffn = 30

[layer_8]
q_proj = 0
v_proj = 34
residual_1 = 0
residual_2 = 1
shortcut_sa = 35
shortcut_ffn = 1

[layer_9]
q_proj = 0
v_proj = 49
residual_1 = 1
residual_2 = 1
shortcut_sa = 48
shortcut_ffn = 1

[layer_10]
q_proj = 0
v_proj = 50
residual_1 = 1
residual_2 = 1
shortcut_sa = 0
shortcut_ffn = 1

[layer_11]
q_proj = 0
v_proj = 2
residual_1 = 1
residual_2 = 1
shortcut_sa = 1
shortcut_ffn = 2

[layer_12]
q_proj = 0
v_proj = 1
residual_1 = 0
residual_2 = 0
shortcut_sa = 19
shortcut_ffn = 1

[layer_13]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 29
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 34
shortcut_ffn = 1

[layer_15]
q_proj = 0
v_proj = 47
residual_1 = 0
residual_2 = 0
shortcut_sa = 50
shortcut_ffn = 50

[layer_16]
q_proj = 0
v_proj = 8
residual_1 = 50
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_17]
q_proj = 0
v_proj = 6
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 50

[layer_18]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 50
shortcut_sa = 50
shortcut_ffn = 50

[layer_19]
q_proj = 0
v_proj = 12
residual_1 = 50
residual_2 = 50
shortcut_sa = 50
shortcut_ffn = 46

[layer_20]
q_proj = 0
v_proj = 50
residual_1 = 3
residual_2 = 33
shortcut_sa = 6
shortcut_ffn = 4

[layer_21]
q_proj = 0
v_proj = 2
residual_1 = 14
residual_2 = 15
shortcut_sa = 10
shortcut_ffn = 26

[layer_22]
q_proj = 0
v_proj = 2
residual_1 = 13
residual_2 = 9
shortcut_sa = 16
shortcut_ffn = 50

[layer_23]
q_proj = 0
v_proj = 3
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 31
