total_reallocation_number = 100

[layer_0]
q_proj = 0
v_proj = 2
residual_1 = 44
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 93
residual_1 = 0
residual_2 = 0
shortcut_sa = 3
shortcut_ffn = 0

[layer_2]
q_proj = 0
v_proj = 93
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 91
residual_1 = 3
residual_2 = 5
shortcut_sa = 52
shortcut_ffn = 8

[layer_4]
q_proj = 0
v_proj = 93
residual_1 = 1
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_5]
q_proj = 0
v_proj = 93
residual_1 = 1
residual_2 = 1
shortcut_sa = 64
shortcut_ffn = 63

[layer_6]
q_proj = 0
v_proj = 97
residual_1 = 4
residual_2 = 41
shortcut_sa = 68
shortcut_ffn = 54

[layer_7]
q_proj = 0
v_proj = 95
residual_1 = 0
residual_2 = 44
shortcut_sa = 73
shortcut_ffn = 43

[layer_8]
q_proj = 0
v_proj = 97
residual_1 = 0
residual_2 = 63
shortcut_sa = 48
shortcut_ffn = 67

[layer_9]
q_proj = 0
v_proj = 97
residual_1 = 38
residual_2 = 86
shortcut_sa = 83
shortcut_ffn = 71

[layer_10]
q_proj = 94
v_proj = 100
residual_1 = 10
residual_2 = 24
shortcut_sa = 2
shortcut_ffn = 34

[layer_11]
q_proj = 0
v_proj = 100
residual_1 = 2
residual_2 = 3
shortcut_sa = 58
shortcut_ffn = 3

[layer_12]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_13]
q_proj = 0
v_proj = 95
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 3

[layer_14]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 39
residual_1 = 0
residual_2 = 1
shortcut_sa = 99
shortcut_ffn = 3

[layer_16]
q_proj = 0
v_proj = 30
residual_1 = 52
residual_2 = 0
shortcut_sa = 97
shortcut_ffn = 5

[layer_17]
q_proj = 0
v_proj = 38
residual_1 = 0
residual_2 = 0
shortcut_sa = 67
shortcut_ffn = 0

[layer_18]
q_proj = 0
v_proj = 44
residual_1 = 7
residual_2 = 5
shortcut_sa = 57
shortcut_ffn = 2

[layer_19]
q_proj = 0
v_proj = 18
residual_1 = 6
residual_2 = 9
shortcut_sa = 47
shortcut_ffn = 4

[layer_20]
q_proj = 0
v_proj = 27
residual_1 = 3
residual_2 = 9
shortcut_sa = 42
shortcut_ffn = 59

[layer_21]
q_proj = 0
v_proj = 38
residual_1 = 25
residual_2 = 12
shortcut_sa = 26
shortcut_ffn = 18

[layer_22]
q_proj = 0
v_proj = 24
residual_1 = 8
residual_2 = 7
shortcut_sa = 15
shortcut_ffn = 11

[layer_23]
q_proj = 0
v_proj = 35
residual_1 = 3
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 0
