# Zero-proxy training & Alpha importance testing
# basics
model = "opt_lora"
dataset = "alpaca"
load_name = "facebook/opt-350m"
load_type = "hf"
metric_red_tolerance = 0.0005
# training
training_optimizer = "adamw"
learning_rate = 2e-4
weight_decay = 0.01
max_epochs = 1
batch_size = 4
log_every_n_steps = 20
# torch lightning
task = "causal_language_modeling"
#num_workers = 0
num_devices = 2
#accelerator = "cpu"
# language model options
is_pretrained = true
project_dir = "./ags_output"
lora_config = "./configs/lora/lora_networkwise.toml"
