# basics
model = "facebook/opt-125m"
dataset = "sst2"
# training
training_optimizer = "adamw"
learning_rate = 2e-5
weight_decay = 0.01
max_epochs = 5
batch_size = 32
log_every_n_steps = 20
# torch lightning
task = "classification"
#num_workers = 0
num_devices = 1
#accelerator = "cpu"
project_dir = "./ags_output"