# basics
model = "facebook/opt-350m"
dataset = "boolq"
# training
training_optimizer = "adamw"
learning_rate = 1e-5
weight_decay = 0.01
max_epochs = 10
batch_size = 16
log_every_n_steps = 20
# torch lightning
task = "classification"
num_workers = 42
num_devices = 2
#accelerator = "cpu"
# language model options
is_pretrained = true
project_dir = "./ags_output"