# basics
model = "opt_lora_ags_layer_residual"
dataset = "mrpc"
load_name = "facebook/opt-350m"
load_type = "hf"
# training
training_optimizer = "adamw"
learning_rate = 2e-4
weight_decay = 0.01
max_epochs = 20
batch_size = 4
log_every_n_steps = 10
# torch lightning
task = "classification"
#num_workers = 0
num_devices = 2
#accelerator = "cpu"
# language model options
is_pretrained = true
project_dir = "./ags_output"
lora_config = "./configs/lora/lora_networkwise.toml"
shortcut_config = "./configs/shortcut/layer_res_networkwise.toml"
