# basics
model = "opt_lora"
dataset = "alpaca"
load_name = "facebook/opt-350m"
load_type = "hf"
# training
training_optimizer = "adamw"
learning_rate = 1e-4
weight_decay = 0.01
max_epochs = 20
batch_size = 4
log_every_n_steps = 20
# torch lightning
task = "causal_language_modeling"
#num_workers = 0
num_devices = 2
#accelerator = "cpu"
# language model options
is_pretrained = true
project_dir = "./ags_output"
lora_config = "./realloc-alpha/alpaca-02-29-version_0.toml"