# basics
model = "facebook/opt-350m"
dataset = "cb"
# training
training_optimizer = "adamw"
learning_rate = 2e-5
weight_decay = 0.01
max_epochs = 10
batch_size = 8
log_every_n_steps = 10
# torch lightning
task = "classification"
#num_workers = 0
num_devices = 2
#accelerator = "cpu"
# language model options
is_pretrained = true
project_dir = "./ags_output"